# Generated by Django 4.2.3 on 2023-07-09 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_entry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
